import { Link } from 'react-router-dom'
import ScoreBar from '../components/ScoreBar.jsx'

const sample = {
  candidate: 'Candidate Name',
  field: 'AI/ML · Fresher',
  duration: '14:32',
  questionCount: 3,
  overall: 78,
  technical: [['Correctness', 80], ['Relevance', 85], ['Depth', 70], ['Problem solving', 74]],
  communication: [['Clarity', 82], ['Structure', 76]],
  knowledge: [['Resume knowledge', 84], ['Project knowledge', 79]],
  speech: [['Speaking rate', '132 wpm'], ['Filler words', '6 per min'], ['Average pause', '1.2 s'], ['Response time', '3.4 s']],
  visual: [['Face visibility', '96%'], ['Camera-facing ratio', '81%'], ['Head movement', '12 per min']],
  strengths: ['Clear explanation of project architecture', 'Relevant, on-topic answers', 'Good awareness of trade-offs'],
  improvements: ['Go deeper on model evaluation metrics', 'Reduce filler words', 'Structure answers with a clear beginning and end'],
  questions: [
    { q: 'Tell me about yourself.', score: 82, feedback: 'Well structured and concise. Mention your main strength earlier.' },
    { q: 'Why did you choose YOLO for your project?', score: 76, feedback: 'Correct reasoning on speed. Missing a comparison with alternatives.' },
    { q: 'Explain overfitting and how you prevent it.', score: 70, feedback: 'Correct definition. Add concrete techniques such as dropout and early stopping.' },
  ],
}

function Card({ title, badge, children }) {
  const measured = badge === 'Measured'
  return (
    <section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
      <div className="mb-4 flex items-center justify-between">
        <h2 className="font-semibold">{title}</h2>
        <span className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${measured ? 'bg-emerald-50 text-emerald-700' : 'bg-brand-500/10 text-brand-600'}`}>
          {badge}
        </span>
      </div>
      {children}
    </section>
  )
}

const Scores = ({ items }) => (
  <div className="space-y-4">{items.map(([label, value]) => <ScoreBar key={label} label={label} value={value} />)}</div>
)

const Metrics = ({ items }) => (
  <dl className="grid grid-cols-2 gap-4">
    {items.map(([label, value]) => (
      <div key={label} className="rounded-xl bg-slate-50 p-4">
        <dt className="text-xs text-slate-500">{label}</dt>
        <dd className="mt-1 text-lg font-semibold">{value}</dd>
      </div>
    ))}
  </dl>
)

const Bullets = ({ items }) => (
  <ul className="list-disc space-y-2 pl-5 text-sm text-slate-600">{items.map((item) => <li key={item}>{item}</li>)}</ul>
)

export default function Report() {
  const r = sample
  return (
    <main className="min-h-screen bg-slate-50 pb-16">
      <header className="bg-navy-900 px-6 py-12 text-white">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-8">
          <div>
            <p className="text-sm text-brand-400">Interview report</p>
            <h1 className="mt-1 text-3xl font-semibold">{r.candidate}</h1>
            <p className="mt-2 text-slate-400">{r.field} · {r.duration} · {r.questionCount} questions</p>
          </div>
          <div
            className="grid size-36 place-items-center rounded-full"
            style={{ background: `conic-gradient(#6d5ef0 ${r.overall * 3.6}deg, rgba(255,255,255,0.1) 0)` }}
          >
            <div className="grid size-28 place-items-center rounded-full bg-navy-900 text-center">
              <span className="text-3xl font-bold">{r.overall}</span>
              <span className="-mt-4 text-xs text-slate-400">overall</span>
            </div>
          </div>
        </div>
      </header>

      <div className="mx-auto mt-8 max-w-6xl space-y-6 px-6">
        <p className="text-sm text-slate-500">
          <strong>Measured</strong> values are calculated from your session. <strong>AI feedback</strong> is generated by a language model and may be imperfect.
        </p>

        <div className="grid gap-6 md:grid-cols-2">
          <Card title="Technical performance" badge="AI feedback"><Scores items={r.technical} /></Card>
          <Card title="Communication" badge="AI feedback"><Scores items={r.communication} /></Card>
          <Card title="Resume and project knowledge" badge="AI feedback"><Scores items={r.knowledge} /></Card>
          <Card title="Speech metrics" badge="Measured"><Metrics items={r.speech} /></Card>
          <Card title="Visual observations" badge="Measured"><Metrics items={r.visual} /></Card>
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          <Card title="Strengths" badge="AI feedback"><Bullets items={r.strengths} /></Card>
          <Card title="Areas for improvement" badge="AI feedback"><Bullets items={r.improvements} /></Card>
        </div>

        <Card title="Question analysis" badge="AI feedback">
          <ul className="divide-y divide-slate-100">
            {r.questions.map((item) => (
              <li key={item.q} className="flex items-start justify-between gap-6 py-4">
                <div>
                  <p className="font-medium">{item.q}</p>
                  <p className="mt-1 text-sm text-slate-600">{item.feedback}</p>
                </div>
                <span className="rounded-full bg-brand-500/10 px-3 py-1 text-sm font-semibold text-brand-600">{item.score}</span>
              </li>
            ))}
          </ul>
        </Card>

        <div className="text-center">
          <Link to="/setup" className="inline-block rounded-full bg-brand-500 px-6 py-3 font-medium text-white transition hover:bg-brand-600">
            New interview
          </Link>
        </div>
      </div>
    </main>
  )
}